# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1be361c60f9435cdb085c97eb67dea187ba70690cfd9bc6686673eb1923fb74d17f6e49bee4730b1c2b8832e62285109365ed177447e1867470d2d179ffd38c1

test:
  secret_key_base: cf5ab9e7902b9e219fb662a5912540251b2dc270387c5b9d22542cebcfd788c809f37fb118268461675f2f875333f2d096540b81bf416eaf90348e94bf914296

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
